### ISSUE TITLE
Integer and Ecc updates

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#134]
There are two things we want to achieve with this task:
1) Use `Chip` and `Chipset` API

For Integers we would use Chips for each arithmetic operation. Similarly to `edwards` chips:
https://github.com/eigen-trust/eigen-trust/blob/master/circuit/src/edwards/mod.rs

For Ecc we want to use Chipset trait.

2) Avoid passing reduction witness to the chips manually. Instead it should be calculated inside the chip.

**Comment by 4rmanc** [comment]
#130
