### ISSUE TITLE
Dynamic sets

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#141]
If we change the set, the current signatures become invalid, forcing users to sign new opinions every time the set changes. To solve this we need an option to:
- Sign sparse arrays - An array containing just the neighbours we want to give scores to, leaving the rest as null or `0`. The reason for null neighbours is that we want to keep the circuit size (set size) constant.
- Pick neighbours from sparse array that are not null AND are members of the group set, and normalise them, so that the sum of them equals to the initial score constant provided by the circuit.

Also consider other routes, where we keep the immutable sets, but have signatures that we default to.

**Comment by lazovicff** [comment]
We will have fixed sets of NUM_NEIGHBOURS = 12 and INITIAL_SCORE = 1000.

At first, the set is empty: `[(pk = null/0, 1000), ...11 times]` - Its not possible to create a valid proof for this case.

When one peer joins: `[(pk = peer1_pk, 1000), ...11 times null]`

When two peer joins: `[(pk = peer1_pk, 1000), (pk = peer2_pk, 1000), ...10 times null]`

Peer1 is going to sign: `[(peer1_pk, 0), (peer1_pk, 1000), ...10 times null]`- for Peer 2 as well

When three peer joins: `[(pk = peer1_pk, 1000), (pk = peer2_pk, 1000), (pk = peer3_pk, 1000), ...9 times null]`

The signature from Peer1 is still valid because all of thieir score is distributed.

Think about cases where:
- Peer 3 did not distribute his scores - can we still make proofs? - Initial opinion - NO.
- What happens when Peer 2 leaves the set - are the existing signatures still valid? Initial opinion - NO.

The problem persists - In most cases where the set changes we cannot make proofs.

**Comment by lazovicff** [comment]
Added more cases to help us think about this:
```
NUM_NEIGHBOURS = 6
INITIAL_SCORE = 1000

1. Case ---------------------------
The set is empty
[
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

2. Case ---------------------------

Peer 1 joins, with signature:
[
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Now, the set looks like:
[
    (pk = peer1_pk, 1000),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Not possible to make proof

3. Case ---------------------------

Peer 1 remains, with signature:
[
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Peer 2 joins, with signature:
[
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Now, the set looks like:
[
    (pk = peer1_pk, 1000),
    (pk = peer2_pk, 1000),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Not possible to make proofs since both Peer 1 and Peer 2 are not distributing their reputation

4. Case ---------------------------

Peer 1 updates the signature:
[
    (pk = null, 0),
    (pk = peer2_pk, 1000),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Peer 2 updates the signature:
[
    (pk = peer1_pk, 1000),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Now, the set looks like:
[
    (pk = peer1_pk, 1000),
    (pk = peer2_pk, 1000),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Now we can make proofs, where Peer 1 and Peer 2 will have equal scores of 1000

5. Case ---------------------------

Peer 1 remains with signature:
[
    (pk = null, 0),
    (pk = peer2_pk, 1000),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Peer 2 remains with signature:
[
    (pk = peer1_pk, 1000),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Peer 3 joins with signature:
[
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Now, the set looks like:
[
    (pk = peer1_pk, 1000),
    (pk = peer2_pk, 1000),
    (pk = peer3_pk, 1000),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
    (pk = null, 0),
]

Not possible to make proofs, since peer3 didn't distribute his signatures
```

**Comment by lazovicff** [comment]
The research is concluded with #154 

The conclusion:
Filtering the sets in sequential order is not possible, some kind of recursive algorithm is needed to accommodate for all the edge cases around invalid opinions. This is not possible to do efficiently inside the circuit.

The solution:
We need to rely on concept of reputation leaking, which means that if a peer distributes a portion of their score to invalid peers, the amount of reputation in the set will get lower (will leak), and the final sum of all the reputation scores will not be the same as starting one.

**Comment by duguorong009** [comment]
@lazovicff 
Can you give more detail to 2nd bullet point? 
I mean `Make an array that circuits will use to ...`.

**Comment by lazovicff** [comment]
Make 2 arrays:
1) Contains the directly invalid peers:
- [1, 4, 6] - indices of directly invalid peers. In the `validate_path` function, go through each and check the validity of their opinions.
- [2, 3, 5] - Go though each index and check the validity of their opinion, by checking all the peers inside their op array.

Have a map of PublicKey => Option<bool>, which is initialised to `None` for all pks. As you loop through path arrays, set them to Some(false) in case of invalid opinion, and Some(true) in case of a valid opinion.

**Comment by lazovicff** [comment]
Copying from discussion:

If the set is [peer1, peer2, peer3], every peer should match this set when giving out their score. If it doesn't match we will just convert it to the right format in the circuit.

Case for giving score to peer that is not in the set:
peer1_op = [(peer5, 2), (peer2, 7), (peer3, 1)] should be converted to [(peer1, 0), (peer2,  7), (peer3, 1)]

Case for giving score to itself:
peer1_op = [(peer1, 2), (peer2, 7), (peer3, 1)] should be converted to [(peer1, 0), (peer2,  7), (peer3, 1)]

Case for all the scores to peers that are not in the set:
peer1_op = [(peer5, 2), (peer6, 7), (peer7, 1)] should be converted to [(peer1, 0), (peer2,  4), (peer3, 4)] - give everyone equal score

Case for giving scores to itself in addition to giving them to peers that are not in the set:
peer1_op = [(peer1, 2), (peer6, 7), (peer7, 1)] should be converted to [(peer1, 0), (peer2,  4), (peer3, 4)] - give everyone equal score

We should also this about when we have sparse array, meaning some peers are null.
We should handle it the same way as when we give the score to ourselves, just replace with 0, normalize the rest
