### ISSUE TITLE
CommonConfig - number of columns

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#173]
Think about how many columns we need to meet the scalability requirements.
Think about if we want to optimise it for smart contract verifiers

**Comment by lazovicff** [comment]
Advice = 20 To fit Integers
Fixed = 11 To fit MainGate, Poseidon, Lookup Tables

We are not optimising for smart contracts

**Comment by duguorong009** [comment]
I have one question. @lazovicff 
If we are going to use Lookup Table, we should introduce the `TableColumn`, like [MockCommonConfig](https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/lt_eq_lookup.rs#L16-L21).
Hence, I think we should use `Advice = 20, Fixed =10, TableColumn = 1`. 
And I add the use of Lookup Table in next PRs.
What do you think?

**Comment by lazovicff** [comment]
Yes, sounds good. That is the plan

**Comment by lazovicff** [comment]
Chips to update:
- Integers
- MainGate
- Set membership
- LessThanEqual

All of these chips should utilise the columns maximally before switching to the next row
