### ISSUE TITLE
Client improvements

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#199]
Tasks:
- [x] Remove MANAGER_STORE, and initialise it inside the main function.
- [ ] Move fs actions inside `main.rs` - the idea is to have multiple choices for storing data. It could be database, memory or cold storage, depending on the needs of the client.
- [x] Merge Client and Manager?
- [x] Client takes too long to initialise

Research:
- [ ] Explore different naming conventions for rust workspaces

**Comment by brech1** [comment]
I would like to add that the client takes too long to initialize, before running any command it just sits there for several seconds. I would like to check that too.

**Comment by brech1** [comment]
I just marked the client initialization time item as done. I would propose to create a two issues for the pending items in this one. Them being:

- Update FS actions
  - Create a `fs.rs` module in the `client` with all fs related functionalities, including those of the circuit. 
  - Enable multiple storage options, such as database, memory or cold storage.
- Project structure
  - Explore different naming conventions for rust workspaces.
  - Enable CLI commands to be executed using the project output from `./target`. This will be possible with the new fs actions in a new file in the `client`.
  - Remove mnemonic from `client-config.json` and move it to a .env file. Also create a .env.origin for an easier project setup.

**Comment by lazovicff** [comment]
I will create a small task for each of these points and prepare them for the next weeks sprint

**Comment by lazovicff** [comment]
@brech1 Moved all of the points to separate task, closing this one
