### ISSUE TITLE
UnassignedValue Trait

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#207]
```rust
trait UnassignedValue {
  fn without_witnesses(&self) -> Self;
}
```

Example:
```rust
struct UnassignedPoint<F: FieldExt> {
  x: Value<F>,
  y: Value<F>
}

impl<F: FieldExt> UnassignedValue for UnassignedPoint<F> {
  fn without_witnesses(&self) -> Self {
    Self { x: Value::unknown(), y: Value::unknown() }
  }
}
```

- Implement this trait for:
  - PublicKey
  - Signature

- Update DynamicSets circuit to use these traits inside `without_witnesses` method.
- Update every test circuit defined inside unit test modules.

**Comment by 4rmanc** [comment]
@lazovicff What do you mean by saying unit test modules? You mentioned that I should implement this for all the test circuits in PR. Is there anything specific?

**Comment by lazovicff** [comment]
https://github.com/eigen-trust/protocol/blob/master/circuit/src/ecc/mod.rs#L1046-L1048
https://github.com/eigen-trust/protocol/blob/master/circuit/src/ecc/mod.rs#L1121-L1123
https://github.com/eigen-trust/protocol/blob/master/circuit/src/ecc/mod.rs#L1193-L1195
https://github.com/eigen-trust/protocol/blob/master/circuit/src/ecc/mod.rs#L1270-L1272
https://github.com/eigen-trust/protocol/blob/master/circuit/src/eddsa/mod.rs#L242-L244
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/bits2num.rs#L150-L152
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/lt_eq.rs#L210-L212
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/lt_eq_lookup.rs#L200-L202
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/main.rs#L734-L736
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/main.rs#L842-L844
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/main.rs#L925-L927
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/main.rs#L1023-L1025
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/main.rs#L1107-L1109
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/main.rs#L1191-L1193
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/main.rs#L1288-L1290
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/main.rs#L1386-L1388
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/range.rs#L490-L492
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/range.rs#L417-L419
https://github.com/eigen-trust/protocol/blob/master/circuit/src/gadgets/range.rs#L344-L346
https://github.com/eigen-trust/protocol/blob/master/circuit/src/integer/mod.rs#L826-L828
https://github.com/eigen-trust/protocol/blob/master/circuit/src/integer/mod.rs#L911-L913
https://github.com/eigen-trust/protocol/blob/master/circuit/src/integer/mod.rs#L981-L983
https://github.com/eigen-trust/protocol/blob/master/circuit/src/integer/mod.rs#L1050-L1052
https://github.com/eigen-trust/protocol/blob/master/circuit/src/integer/mod.rs#L1119-L1121
https://github.com/eigen-trust/protocol/blob/master/circuit/src/merkle_tree/mod.rs#L169-L171
https://github.com/eigen-trust/protocol/blob/master/circuit/src/verifier/transcript/mod.rs#L453-L455
https://github.com/eigen-trust/protocol/blob/master/circuit/src/verifier/transcript/mod.rs#L567-L569
https://github.com/eigen-trust/protocol/blob/master/circuit/src/verifier/transcript/mod.rs#L649-L651
https://github.com/eigen-trust/protocol/blob/master/circuit/src/verifier/transcript/mod.rs#L794-L796
