### ISSUE TITLE
Experiment with `converge_rational` results

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#228]
Currently, the `check_threshold` function accepts constants `NUM_LIMBS` and `POWER_OF_TEN`, which need to be determined by the developer beforehand. These constants depend on the `NUM_NEIGHBOURS`, `NUM_ITERATION` and the values inside the opinion of each peer.

Our goal: Given the constants `NUM_NEIGHBOURS` and `NUM_ITERATION` find the constants `NUM_LIMBS` and `POWER_OF_TEN`, such that they work for every possible value used inside the opinion matrix

**Comment by duguorong009** [comment]
I've done several experiments, varying the params related to `converge_rational`.
Here are some results we can check, and have some insights.

|   score   |  NUM_NEIGHBORS    |    NUM_LIMBS      |
|  :---: | :---: |  :---:  |
|     u8     |               32                   |            14             |
|              |               64                   |            30             |
|              |              128                  |            58             |
|    u16    |               32                   |            25             |
|              |               64                   |            50             |
|              |              128                  |           104            |
|   u32     |               32                   |            50             |
|              |               64                   |            98             |
|              |              128                  |           197            |
|   u64     |               32                   |            96             |
|              |               64                   |           190            |
|              |              128                  |          < 300          |
```
Constants:
NUM_ITERATIONS = 30
INITIAL_SCORE = 1000
POWER_OF_TEN = 100
``` 
The `score` column represents the range of values the `score` can take.
All the `score` values are obtained using randon number generation.

One possible issue:
In some experiments, the `compose` and `decompose` of `BigRational` value went wrong.
It means that the comparison also went wrong, and the `is_bigger` values are not correct.
I suspect that this error is attributed to selection of `POWER_OF_TEN` value.
But, in most cases, current `POWER_OF_TEN`(1000) worked well. (Correct comparison result)

**Comment by lazovicff** [comment]
@duguorong009 That is the exact problem we are trying to solve, which is:

Given the fixed NUM_NEIGHBORS and NUM_LIMBS, find NUM_LIMBS and POWER_OF_TEN such that it works for any value.
In addition, two things to note: 
- scale the numerator and denominator so that we can work with small numbers.
- the POWER_OF_TEN should be larger than NUM_NEIGHBORS * INITIAL_SCORE - you can do experiments to understand why we need this constraint

**Comment by lazovicff** [comment]
For now we should focus on 2 cases:
1) NUM_NEIGHBORS = 4 , NUM_ITERATIONS = 30, & INITIAL_SCORE = 1000
2) NUM_NEIGHBORS = 128 , NUM_ITERATIONS = 30, & INITIAL_SCORE = 1000
