### ISSUE TITLE
Forbid unnecessary cloning using Clippy

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#240]
Add rust clippy rule that forbids unnecessary cloning (gives a compile error), and fix all occurrences of this error.

**Comment by brech1** [comment]
What do you think about adding a `.clippy.toml` file and make the rules for both the client and the circuit?

 - https://github.com/eigen-trust/protocol/blob/8600bac2780e6a58d591d1c2899841a1cef390e5/circuit/src/lib.rs#L3
 
Adding these to the clippy configuration file and then adding the unnecesary cloning deny rule.

**Comment by brech1** [comment]
It seems that `rustc` lint rules can't be added to a configuration file... yet. 

- https://github.com/rust-lang/cargo/issues/5034
- https://github.com/rust-lang/cargo/issues/12115

And also, only these clippy rules are allowed in the `clippy.toml` file:

- https://doc.rust-lang.org/nightly/clippy/lint_configuration.html

Clippy lints, such as:

- tabs_in_doc_comments
- panic
- unnecessary_cast
- cast_lossless
- cast_possible_wrap

Have to be implemented using the derive macro format.

I can add these rules to the client lib! And also the unnecessary cloning rule.
