### ISSUE TITLE
KZG Commitments + Elliptic Curves

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#340]
KZG commitments (Vector commitments):
- The end goal is to provide an example KZG commitment over a n-length polynomial. The example should include:
  - Test that uses EC types from Halo2 (field elements)

Elliptic curves:
- Provide the main characteristic of elliptic curves
- Provide a document that lists all the types and forms of elliptic curves:
  - Define Edwards, Twisted-Edwards, Montgomery, Weierstrass
  - Projective, Affine and Extended
  - Research what curves can be used for Ecdsa and Eddsa and why

**Comment by 4rmanc** [comment]
@lazovicff I used [this](https://dankradfeist.de/ethereum/2020/06/16/kate-polynomial-commitments.html) article to study the KZG.

**Comment by 4rmanc** [comment]
KZG [implementation](https://github.com/4rmanc/kzg_halo2) with Halo2 EC types

**Comment by 4rmanc** [comment]
For the EC research, these [notes](https://crypto.stanford.edu/pbc/notes/) can be good knowledge source for the document. 
Also, this [article](https://static1.squarespace.com/static/5fdbb09f31d71c1227082339/t/5ff394720493bd28278889c6/1609798774687/PairingsForBeginners.pdf) has basic details about the pairing and elliptic curves.
I love this Elliptic Curve [explanation](https://zcash.github.io/halo2/background/curves.html) from Zcash. I read this before the presentation in the Belgrade and it helped me a lot :D

**Comment by lazovicff** [comment]
https://hackmd.io/dU3vUwqAQqGqn0KyrqUXRQ?both

Code for KZG: https://github.com/4rmanc/kzg_halo2
