### ISSUE TITLE
Use the native Threshold circuit for Bandada checks

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/protocol#345]
On this line:
https://github.com/eigen-trust/protocol/blob/master/eigentrust-cli/src/cli.rs#L234

We are just taking the score and doing normal comparison check.
We want to use the Threshold native circuit: https://github.com/eigen-trust/protocol/blob/master/eigentrust-zk/src/circuits/threshold/native.rs

`score: F, ratio: BigRational, threshold: F` are the values loaded from the file

The properties of the struct are going to be useful for the circuit public and private inputs: https://github.com/eigen-trust/protocol/blob/master/eigentrust-zk/src/circuits/threshold/native.rs#L18-L21

This function: https://github.com/eigen-trust/protocol/blob/master/eigentrust-zk/src/circuits/threshold/native.rs#L60-L96 should replace the comparison check

**Comment by brech1** [comment]
Resolved in #347
